# Generated by Django 3.1.7 on 2021-04-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar', '0002_auto_20210406_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='level',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=6),
        ),
    ]
