# Generated by Django 3.1.7 on 2021-04-09 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guitar', '0003_auto_20210407_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='chord',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
